/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#8bd6b6",
        "on-surface-variant": "#45464d",
        "on-primary-container": "#7b83a0",
        "outline": "#76767e",
        "background": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#002116",
        "secondary-container": "#5bb8fe",
        "slate-border": "#E2E8F0",
        "inverse-primary": "#bec5e5",
        "polar-midnight-deep": "#0B132B",
        "on-surface": "#0b1c30",
        "on-error": "#ffffff",
        "on-secondary-fixed-variant": "#004b73",
        "inverse-on-surface": "#eaf1ff",
        "surface": "#f8f9ff",
        "aurora-emerald": "#10B981",
        "on-tertiary-fixed-variant": "#00513b",
        "surface-dim": "#cbdbf5",
        "glacial-sky": "#38BDF8",
        "on-tertiary-fixed": "#002116",
        "on-secondary-container": "#00476e",
        "ice-white": "#F8FAFC",
        "slate-border-strong": "#CBD5E1",
        "primary": "#0B132B",
        "on-background": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#bec5e5",
        "primary-container": "#131a33",
        "on-primary-fixed": "#131a33",
        "secondary": "#006398",
        "draft-amber-bg": "#FEF3C7",
        "aurora-cyan": "#06B6D4",
        "polar-navy-surface": "#1C2541",
        "inverse-surface": "#213145",
        "surface-variant": "#d3e4fe",
        "tertiary-fixed": "#a6f2d1",
        "error-container": "#ffdad6",
        "surface-container-high": "#dce9ff",
        "surface-bright": "#f8f9ff",
        "error": "#ba1a1a",
        "on-secondary-fixed": "#001d31",
        "outline-variant": "#c6c6ce",
        "pure-white": "#FFFFFF",
        "azure-accent": "#0EA5E9",
        "on-primary-fixed-variant": "#3e4660",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-tertiary-container": "#479175",
        "surface-container": "#e5eeff",
        "secondary-fixed": "#cce5ff",
        "surface-container-highest": "#d3e4fe",
        "surface-tint": "#565d79",
        "draft-amber-text": "#92400E",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#93ccff",
        "draft-amber-border": "#F59E0B",
        "tertiary": "#000000",
        border: "#E2E8F0",
        input: "#CBD5E1",
        ring: "#0EA5E9",
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "code-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Inter", "sans-serif"],
        display: ["Plus Jakarta Sans", "sans-serif"],
      }
    }
  },
  plugins: [],
};
